= Welcome

IMPORTANT: Due to COVID-19 situation, the course will be held online in Spring 2021. All lectures and tutorials will happen over teams. 

IMPORTANT: The course is currently under development. Although the information presented here is mostly accurate if you want to know the general course information, but details, such as grading and project details will be likely changed and you should not rely on them. Everything can change. 

Welcome to the new Code Generators course!

= Schedule

[%autowidth]
|===
| # | Lecture | Tutorial | Project  

| 1 
| link:media/NI-GEN-1.pdf[Compiler Overview]
|
|

| 2
| link:media/NI-GEN-2.pdf[Principles of Compiled Code]
| Target Architectures Overview
| 

| 3
| tinyC language and tiny86 target (live coding)
| 
|


| 4
| link:media/NI-GEN-4.pdf[Internal Representations]
| Syntax-Directed Translation to IR
|

| 5
| Semantic Analysis (live coding)
| 
|

| 6
| link:media/NI-GEN-6.pdf[Modern Compilers]
| Q&A: Internal Representation & Translation 
|

| 7
| link:media/NI-GEN-7.pdf[Instruction Selection]
|
|

| 8
| link:http://selfie.cs.uni-salzburg.at[Selfie] (Guest Lecture)
| cancelled
| minimal compilation to IR

| 9
| cancelled
|
|

| 10
| link:media/NI-GEN-8.pdf[Register Allocation]
| Q&A Offline
|

| 11 
| Compiler Optimizations I (no slides)
| 
| 

| 12
| Compiler Optimizations and Analysis II )(no slides)
| Q&A Offline
|

|===

== Languages

Since the coursework is a `C`-like language compiler written in `C++`, familiarity with `C++` is essential.

_All course materials materials (including this webpage) will be in English, but lectures and tutorials themselves will be in Czech (optionally, if we get english-only speaking students, we will use English as well). You can use Czech/English freely_. 







