= Welcome

IMPORTANT: Due to COVID-19 situation, the course will be held online in Spring 2021. All lectures and tutorials will happen over teams. 

IMPORTANT: The course is currently under development. Although the information presented here is mostly accurate if you want to know the general course information, but details, such as grading and project details will be likely changed and you should not rely on them. Everything can change. 

Welcome to the new Code Generators course!

= Schedule

[%autowidth]
|===
| # | Lecture | Tutorial | Project  

| 1 
| link:media/NI-GEN-1.pdf[Compiler Overview]
|
|

| 2
| Principles of Compiled Code
| tinyC Language and tiny86 VM
|

| 3
| Semantic Analysis
|
|

| 4
| Translation
| Q&A: Frontend and Translation
|

| 5
| Internal Representations
| 
|

| 6 
| Optimization I
| Q&A: Internal Representation
| minimal compilation 

| 7
| Optimization II
|
|

| 8
| Register Allocation, Instruction Selection & Scheduling, Code Layout & Generation
| Q&A: IR Optimizations 
|

| 9
| Compilation of Advanced Constructs
|
|

| 10 
| Case Study - LLVM Compiler
| Q&A: Backend
| full unoptimized, some IR opts

| 11
| Just-in-Time Compilation
|
|

| 12
| Debugging Support
| Q&A: Advanced Techniques
| Backend Optimizations
|===

== Languages

Since the coursework is a `C`-like language compiler written in `C++`, familiarity with `C++` is essential.

_All course materials materials (including this webpage) will be in English, but lectures and tutorials themselves will be in Czech (optionally, if we get english-only speaking students, we will use English as well). You can use Czech/English freely_. 







