= Welcome

////
Guest Lecture
Reserve

Introduction to compiler (1)
Internal Representations (4) - Intro to TinyC
Principles of compiled code (2a)
Modern Compilers (6) - TinyC translation to IR
Semantic Analysis (Live Coding)
Targets (2b) - Tiny86 Intro, basic translation
Instruction Selection (7) 
Register Allocation (8) - IR to Tiny86, advanced
Optimizations (I) 
Optimizations (II) - Q&A


tinyC language and tiny86 target (live coding)

////

Welcome to the new Code Generators course! This is the second year of the course, and while a lot of the initial rough edges are hopefully polished by now, the course is still in development. Any suggestions towards the presented topics, project, or course in general are greatly appreciated!

= Schedule

[%autowidth]
|===
| # | Lecture | Tutorial | Project  

| 1 
| Course Introduction, Compiler Overview
| Introduction to TinyC
| Clone & build repo



| 2 
| Semantic Analysis
| 
| Add simple typechecking


| 3
| Internal Representations
| Semantic Analysis II, IR Translation 
| Add more complex typechecking, start with IL

| 4
| Principles of Compiled Code
| 
| Finalize typechecking, simple translation to IL

| 5
| Modern Compilers
| IR Translation II
| Finish IL translation

| 6
| Targets
| Tiny86
| 

| 7 
| Syntax Driven Translation
| 
| Simple calculator from source to backend

| 8 
| Target Translation
| Tiny86, basic translation
| Simple calculator from source to target

| 9
| Instruction Selection
|
| 

| 10
| Register Allocation
| Advanced Target Translation
| Control flow, function calls

| 11
| Optimizations I
|
| Unlimited registers via spilling

| 12
| Optimizations II
| Project Q&A
| More advanced features (note that deadline is the exam)


|===

== Languages

Since the coursework is a `C`-like language compiler written in `pass:[C++]`, familiarity with `pass:[C++]` is essential.

_All course materials materials (including this webpage) will be in English, but lectures and tutorials themselves will be in Czech (optionally, if we get english-only speaking students, we will use English as well)._ 







