= Lectures


_The following list gives a brief information about the main lectures and topics. Note that their actual order is subject to change:_

==== Overview of a Compiler

_Basic overview of a modern compiler and its consituent parts (frontend, middleend, backend, object files, linker, assembler) and recap of basic features. Coursework and course information._

==== Internal Representations

_Introduction and analysis of advantages and disadvantages of various internal representations (Stack Based, 3AC, SSA, Sea of Nodes). Design of intermediate representation suitable for `tinyC`. Control and Data Flow graphs._  

==== Principles of Compiled Code

_Details about how compiled code actually works. Information about calling conventions, stack frames, variables, symbols and visibility. Memory areas (heap, stack, globals), alignment. Compilation units (modules, functions, basic blocks). Object files, static vs dynamic linkage, etc._

==== Modern Compilers

_Internal representations and basic design choices of modern compilers, namely GCC and LLVM._

==== Semantic Analysis

_Scopes and their checking. Symbol table. Inference rules. Types and type checking._

==== Targets

_CISC, RISC and other main architectures and their effects on compiler design and operation._

==== Instruction Selection

_Instruction Selection techniques. Tree tiling, peephole instruction selection. Superopimizers._

==== Register Allocation

_Register allocation and assignment. Local and Global register allocation algorithms - top down, bottom up, greedy, graph coloring. Value spilling.   

==== Compiler Optimizations I

_Optimizing compilers. Local and global optimizations. Description of most important optimizations._

==== Compiler Optimizations II

_Partial Evaluation. Futamura Projections. Practical Introduction to Abstract Interpretation._

==== Selfie (Guest Lecture, might be online)

_Guest lecture by link:http://cs.uni-salzburg.at/~ck/[Christoph Kirsch] about the Selfie, a self-compiling compiler for RISC-V._

==== Projects

_Introduction to course projects and design choices made by the respective teams._



//==== 8 - Optimization

//_An introduction to the intermediate representation optimizer. Local vs Global optimizations. Description of various optimizations, such as peepholer, constant propagation, alias analysis, inlining, loop unrolling, etc. and how they are calculated for the different intermediate representations. The analysis-optimization relationship and scheduling. Link-Time Optimization (LTO) and Profile-Guided-Optimization (PGO)._

//==== 8 - Register Allocation, Instruction Selection & Scheduling, Code Layout & Generation

//_Register allocation techniques. The importance of instruction selection, scheduling and code //layout. Generation of machine code or assembler._

//==== 9 - Target Translation.

//_Compiling to target architecture. Patchpoints, register spilling. Compilation of advanced language constructs (objects, virtual functions & dispatch, exceptions, templates). Zero-cost abstractions._

//==== 10 - Case Study - LLVM Compiler Infrastructure

//_Introduction to LLVM, how it approaches the things we said so far. I.e. the overview of the IR, interesting instructions. How optimizations are done (scheduler, etc). Backend support. Comparison of other compiler suites_

// Done by me, unless Andrea wants to

//==== 11 - Just-in-Time Compilation [MID]

//_Introduction to JIT. Speculative Execution, Multi-tier architecture. Patchpoints. GC. Languages that suppport JIT compilers (JavaScript, Java, Julia, .NET)._

// Guest lecture by Oli

//==== 12 - Debugging Support

//_How to debug compiled code. Breakpoints. Debugging symbols. Debugging optimized code._

