= Classification

_There is a reasonably large course project (60% of the grade) and a final exam (40% of the grade)_

==== Project

The course project is to implement a minimally optimizing compiler for `tinyC`, a simple c-like language. There is a baseline functionality that each compiler must support on top of which you must choose and implement a few more advanced topics. Points are awarded for the completion of the baseline functionality and for finishing the selected extra features. Additional points will be given to fastest and most memory efficient implementations. 

NOTE: As this is first year of the course, details about the project will be added throughout the term. 

==== Exam

The exam consists of two parts, a written test where you will be asked about the theoretical algorithms covered in the lectures and and an oral part where you answers from the test will be discussed. 

Each student has 3 exam takes. If you fail the course, you can (must if it is a compulsory course in your program) attempt to study it one more time, at which point you _must_ pass the course, or you fail your whole study program.

==== Final Marks

Classification is governed by http://www.cvut.cz/pracoviste/pravni-odbor/dokumenty/studijni-predpisy/studijnirad.pdf[Study and Examination Rules].

[options="autowidth"]
|====
<h| Mark  <h| Points
| A       | 90 and more     
| B       ^|   80 - 89
| C       ^|   70 - 79
| D       ^|   60 - 69
| E       ^|   50 - 59
| F       | less than 50 (fail)
|====

==== Conduct

Throughout the course, you are expected to finish all tasks on your own. You are encouraged to discuss your solutions with other students, but all work you submit must be your own and all code submissions will be accompanied by questions about the code you must be able to answer. 

Any attempts to cheat will be dealt with according to the rules above, and may cost you a mark from the course.

