= Project

WARNING: The project is a large part of the grade (60%) and is a lot of work. You should start developing it early and make a regular progress throughout the term.

The beauty of compilers comes in part from the fact that here, the saying that _"the devil lies in the details"_ is more pronounced than in many other parts of CS. This is something that cannot be taught in lectures alone, but requires a lot of own work. 

To this end the term-long project is an implementation of a small `C`-like language for our idealized backend. This consists of finishing a parser, translating the ASTs to an intermediate language of your design, performing various optimizations and then producing target assembly, i.e. a very brief taste of all the main things compiler has to do.

## Formalities

You must create a git repo for your project (gitlab at CTU is preferred, but you can use any git hosting to which we can get read access). Work in the project must be yours and should be incremental, i.e. git log should show a reasonable number of commits for the different features. 

To hand in the project, book a date _before_ your exam with your instructor or TA. 

Make sure to follow some reasonable development practices. It will make the development easier for you and grading easier for us.

#### Teams 

Students may work on their own compilers on their own, or can team up (up to 3 people in a team). When working in a team, the project scope does not change, but students may split the work, in which case it is expected the level of detail and features supported will be greater. In plain English: If you work in a team, you become responsible for one part of the compiler and must implement that part more thoroughly. The ammount of work is expected to be the same, but you will end up with more complete compiler. 

All teams must be arranged before the start of the coursework and responsibilities split explicitly. 

## Project topic

By default, students are expected to implement an optimizing compiler for the `tinyC` language that will generate machine code for the `t86` target. You will be provided with a working `tinyC` lexer and parser and are expected to implement your compiler in `C++`. 

However, alternate projects are encouraged as well. You can alter the input language (as long as it remains interesting), or the implementation language (you might have to write your own parser), or both. The `t86` target supports text input so no `C++` bindings are necessary. 

You can also focus on other than `t86` architecture, but bear in mind this is strictly more work and more perilous journey.  

NOTE: Since the projects are lot of work to begin with, a lot of them can be developed into a master thesis. Talk to us if you might be interested in pursuing this. 

