= Specification

The larger the project, the harder it is to correctly expect the necessary time investment. Even more so if you are studying the concepts used at the same time. We have therefore structured the project specification and grading to minimize the chance that you will fail the course based on insufficient coursework:

== Minimal Requirements (30 pts)

Your implementation must at least be able to do the following, all of which together is worth 30points:

- `int` and `int*` data types only
- basic constructs (`if`, `for`, `while`, `do while`)
- functions
- at least one local (such as strength reduction) and one global optimization (such as inlining) 
- compilation to tiny86 with register spilling

== Additional Features (30 pts)

After the minimum requirements, you may mix & match more advanced features from the list below for up to 30 points. Note that the list is not exhaustive, if you have your own ideas, come to us first:

- `double`, `bool`, `char` types (5pts)
- structs (5pts)
- function pointers (5pts)
- recursive pointers (such as `int**`) (10pts)
- all language constructs (including casts, switch, etc.) (5pts)
- more complex analyses (loop unrolling, loop-invariant code motion, etc., 5-20pts based on complexity)
- smart register allocation (10pts)
- RISC instructions (5pts)
- VLIW instructions (10pts)
- exceptions (20pts)
- Object Oriented layer (30pts)

== SuperExtraAdditional features (20pts)

In _rare_ circumstances, and in cases when the code quality of your solutions is good enough to be added to the tinyc repository to help next iterations of the course, the instruct _may_ (i.e. not guaranteed at all) award up to 20 extra points for such effort. 


